In [1]:
import pandas as pd
pd.set_option('display.max_columns', 50)

import numpy as np
import matplotlib as mp
import matplotlib.pyplot as mplt
import seaborn as sn
from scipy import stats

import sklearn
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
#from sklearn.grid_search import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix , classification_report , f1_score

In [2]:
df_i = pd.read_csv("test_identity.csv")
df_t = pd.read_csv("test_transaction.csv")

In [3]:
df_i.shape

(141907, 41)

In [4]:
df_t.shape

(506691, 393)

The transaction train set initally had 394 features

In [5]:
df_t.columns

Index(['TransactionID', 'TransactionDT', 'TransactionAmt', 'ProductCD',
       'card1', 'card2', 'card3', 'card4', 'card5', 'card6',
       ...
       'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338',
       'V339'],
      dtype='object', length=393)

In [6]:
for column in df_i:
    btao = df_i[column].isna().sum()
    btao2 = (btao * 100)/len(df_i)
    print(column + " -> " + str(btao2) + ' %')

TransactionID -> 0.0 %
id-01 -> 0.0 %
id-02 -> 3.474810967746482 %
id-03 -> 53.151712036756464 %
id-04 -> 53.151712036756464 %
id-05 -> 5.043443945682736 %
id-06 -> 5.043443945682736 %
id-07 -> 96.43498911258783 %
id-08 -> 96.43498911258783 %
id-09 -> 47.614987280401955 %
id-10 -> 47.614987280401955 %
id-11 -> 3.6143389684793563 %
id-12 -> 0.0 %
id-13 -> 8.189166144023902 %
id-14 -> 49.71565884699134 %
id-15 -> 3.4741062808740937 %
id-16 -> 11.38773985779419 %
id-17 -> 4.1865447088586185 %
id-18 -> 64.14905536724757 %
id-19 -> 4.228825921201914 %
id-20 -> 4.421205437363907 %
id-21 -> 96.43498911258783 %
id-22 -> 96.43287505197065 %
id-23 -> 96.43287505197065 %
id-24 -> 96.65978422487967 %
id-25 -> 96.44908285003558 %
id-26 -> 96.44344535505648 %
id-27 -> 96.43287505197065 %
id-28 -> 3.6143389684793563 %
id-29 -> 3.6143389684793563 %
id-30 -> 50.20753028391834 %
id-31 -> 3.722156059954759 %
id-32 -> 50.199074041449684 %
id-33 -> 50.199074041449684 %
id-34 -> 49.139224985377744 %
id-35 -> 3.4741062808740937 %
id-36 -> 3.4741062808740937 %
id-37 -> 3.4741062808740937 %
id-38 -> 3.4741062808740937 %
DeviceType -> 3.5065218770039532 %
DeviceInfo -> 18.92084252362463 %

In [7]:
for column in df_t:
    btao = df_t[column].isna().sum()
    btao2 = (btao * 100)/len(df_t)
    print(column + " -> " + str(btao2) + ' %')

TransactionID -> 0.0 %
TransactionDT -> 0.0 %
TransactionAmt -> 0.0 %
ProductCD -> 0.0 %
card1 -> 0.0 %
card2 -> 1.7079442895176744 %
card3 -> 0.5924715457744464 %
card4 -> 0.6090496969553436 %
card5 -> 0.8973911121373777 %
card6 -> 0.593458340487595 %
addr1 -> 12.948522866993887 %
addr2 -> 12.948522866993887 %
dist1 -> 57.47427919580178 %
dist2 -> 92.8090295663432 %
P_emaildomain -> 13.655659958436207 %
R_emaildomain -> 73.18484046489873 %
C1 -> 0.0005920768278891869 %
C2 -> 0.0005920768278891869 %
C3 -> 0.0005920768278891869 %
C4 -> 0.0005920768278891869 %
C5 -> 0.0005920768278891869 %
C6 -> 0.0005920768278891869 %
C7 -> 0.0005920768278891869 %
C8 -> 0.0005920768278891869 %
C9 -> 0.0005920768278891869 %
C10 -> 0.0005920768278891869 %
C11 -> 0.0005920768278891869 %
C12 -> 0.0005920768278891869 %
C13 -> 0.9370602596059532 %
C14 -> 0.0005920768278891869 %
D1 -> 1.1902717829998954 %
D2 -> 46.33376160223884 %
D3 -> 40.0918903236884 %
D4 -> 15.167232100037301 %
D5 -> 44.28241275254544 %
D6 -> 75.37295906183454 %
D7 -> 88.13221470284651 %
D8 -> 85.32873092279121 %
D9 -> 85.32873092279121 %
D10 -> 2.47586793528995 %
D11 -> 34.837405835114495 %
D12 -> 86.33210378712074 %
D13 -> 75.64906422257351 %
D14 -> 77.265433962711 %
D15 -> 2.381925078598199 %
M1 -> 34.861286267172694 %
M2 -> 34.861286267172694 %
M3 -> 34.861286267172694 %
M4 -> 46.92110181550491 %
M5 -> 61.10864412432824 %
M6 -> 31.36803298262649 %
M7 -> 46.38290397895364 %
M8 -> 46.38014095375683 %
M9 -> 46.38014095375683 %
V1 -> 34.837405835114495 %
V2 -> 34.837405835114495 %
V3 -> 34.837405835114495 %
V4 -> 34.837405835114495 %
V5 -> 34.837405835114495 %
V6 -> 34.837405835114495 %
V7 -> 34.837405835114495 %
V8 -> 34.837405835114495 %
V9 -> 34.837405835114495 %
V10 -> 34.837405835114495 %
V11 -> 34.837405835114495 %
V12 -> 2.4845517287656578 %
V13 -> 2.4845517287656578 %
V14 -> 2.4845517287656578 %
V15 -> 2.4845517287656578 %
V16 -> 2.4845517287656578 %
V17 -> 2.4845517287656578 %
V18 -> 2.4845517287656578 %
V19 -> 2.4845517287656578 %
V20 -> 2.4845517287656578 %
V21 -> 2.4845517287656578 %
V22 -> 2.4845517287656578 %
V23 -> 2.4845517287656578 %
V24 -> 2.4845517287656578 %
V25 -> 2.4845517287656578 %
V26 -> 2.4845517287656578 %
V27 -> 2.4845517287656578 %
V28 -> 2.4845517287656578 %
V29 -> 2.4845517287656578 %
V30 -> 2.4845517287656578 %
V31 -> 2.4845517287656578 %
V32 -> 2.4845517287656578 %
V33 -> 2.4845517287656578 %
V34 -> 2.4845517287656578 %
V35 -> 15.16782417686519 %
V36 -> 15.16782417686519 %
V37 -> 15.16782417686519 %
V38 -> 15.16782417686519 %
V39 -> 15.16782417686519 %
V40 -> 15.16782417686519 %
V41 -> 15.16782417686519 %
V42 -> 15.16782417686519 %
V43 -> 15.16782417686519 %
V44 -> 15.16782417686519 %
V45 -> 15.16782417686519 %
V46 -> 15.16782417686519 %
V47 -> 15.16782417686519 %
V48 -> 15.16782417686519 %
V49 -> 15.16782417686519 %
V50 -> 15.16782417686519 %
V51 -> 15.16782417686519 %
V52 -> 15.16782417686519 %
V53 -> 2.545733000980874 %
V54 -> 2.545733000980874 %
V55 -> 2.545733000980874 %
V56 -> 2.545733000980874 %
V57 -> 2.545733000980874 %
V58 -> 2.545733000980874 %
V59 -> 2.545733000980874 %
V60 -> 2.545733000980874 %
V61 -> 2.545733000980874 %
V62 -> 2.545733000980874 %
V63 -> 2.545733000980874 %
V64 -> 2.545733000980874 %
V65 -> 2.545733000980874 %
V66 -> 2.545733000980874 %
V67 -> 2.545733000980874 %
V68 -> 2.545733000980874 %
V69 -> 2.545733000980874 %
V70 -> 2.545733000980874 %
V71 -> 2.545733000980874 %
V72 -> 2.545733000980874 %
V73 -> 2.545733000980874 %
V74 -> 2.545733000980874 %
V75 -> 2.3842933859097557 %
V76 -> 2.3842933859097557 %
V77 -> 2.3842933859097557 %
V78 -> 2.3842933859097557 %
V79 -> 2.3842933859097557 %
V80 -> 2.3842933859097557 %
V81 -> 2.3842933859097557 %
V82 -> 2.3842933859097557 %
V83 -> 2.3842933859097557 %
V84 -> 2.3842933859097557 %
V85 -> 2.3842933859097557 %
V86 -> 2.3842933859097557 %
V87 -> 2.3842933859097557 %
V88 -> 2.3842933859097557 %
V89 -> 2.3842933859097557 %
V90 -> 2.3842933859097557 %
V91 -> 2.3842933859097557 %
V92 -> 2.3842933859097557 %
V93 -> 2.3842933859097557 %
V94 -> 2.3842933859097557 %
V95 -> 0.0 %
V96 -> 0.0 %
V97 -> 0.0 %
V98 -> 0.0 %
V99 -> 0.0 %
V100 -> 0.0 %
V101 -> 0.0 %
V102 -> 0.0 %
V103 -> 0.0 %
V104 -> 0.0 %
V105 -> 0.0 %
V106 -> 0.0 %
V107 -> 0.0 %
V108 -> 0.0 %
V109 -> 0.0 %
V110 -> 0.0 %
V111 -> 0.0 %
V112 -> 0.0 %
V113 -> 0.0 %
V114 -> 0.0 %
V115 -> 0.0 %
V116 -> 0.0 %
V117 -> 0.0 %
V118 -> 0.0 %
V119 -> 0.0 %
V120 -> 0.0 %
V121 -> 0.0 %
V122 -> 0.0 %
V123 -> 0.0 %
V124 -> 0.0 %
V125 -> 0.0 %
V126 -> 0.0 %
V127 -> 0.0 %
V128 -> 0.0 %
V129 -> 0.0 %
V130 -> 0.0 %
V131 -> 0.0 %
V132 -> 0.0 %
V133 -> 0.0 %
V134 -> 0.0 %
V135 -> 0.0 %
V136 -> 0.0 %
V137 -> 0.0 %
V138 -> 85.04315253280599 %
V139 -> 85.04315253280599 %
V140 -> 85.04315253280599 %
V141 -> 85.04315253280599 %
V142 -> 85.04315253280599 %
V143 -> 84.98986561829597 %
V144 -> 84.98986561829597 %
V145 -> 84.98986561829597 %
V146 -> 85.04315253280599 %
V147 -> 85.04315253280599 %
V148 -> 85.04315253280599 %
V149 -> 85.04315253280599 %
V150 -> 84.98986561829597 %
V151 -> 84.98986561829597 %
V152 -> 84.98986561829597 %
V153 -> 85.04315253280599 %
V154 -> 85.04315253280599 %
V155 -> 85.04315253280599 %
V156 -> 85.04315253280599 %
V157 -> 85.04315253280599 %
V158 -> 85.04315253280599 %
V159 -> 84.98986561829597 %
V160 -> 84.98986561829597 %
V161 -> 85.04315253280599 %
V162 -> 85.04315253280599 %
V163 -> 85.04315253280599 %
V164 -> 84.98986561829597 %
V165 -> 84.98986561829597 %
V166 -> 84.98986561829597 %
V167 -> 73.01432233846664 %
V168 -> 73.01432233846664 %
V169 -> 73.08517419887072 %
V170 -> 73.08517419887072 %
V171 -> 73.08517419887072 %
V172 -> 73.01432233846664 %
V173 -> 73.01432233846664 %
V174 -> 73.08517419887072 %
V175 -> 73.08517419887072 %
V176 -> 73.01432233846664 %
V177 -> 73.01432233846664 %
V178 -> 73.01432233846664 %
V179 -> 73.01432233846664 %
V180 -> 73.08517419887072 %
V181 -> 73.01432233846664 %
V182 -> 73.01432233846664 %
V183 -> 73.01432233846664 %
V184 -> 73.08517419887072 %
V185 -> 73.08517419887072 %
V186 -> 73.01432233846664 %
V187 -> 73.01432233846664 %
V188 -> 73.08517419887072 %
V189 -> 73.08517419887072 %
V190 -> 73.01432233846664 %
V191 -> 73.01432233846664 %
V192 -> 73.01432233846664 %
V193 -> 73.01432233846664 %
V194 -> 73.08517419887072 %
V195 -> 73.08517419887072 %
V196 -> 73.01432233846664 %
V197 -> 73.08517419887072 %
V198 -> 73.08517419887072 %
V199 -> 73.01432233846664 %
V200 -> 73.08517419887072 %
V201 -> 73.08517419887072 %
V202 -> 73.01432233846664 %
V203 -> 73.01432233846664 %
V204 -> 73.01432233846664 %
V205 -> 73.01432233846664 %
V206 -> 73.01432233846664 %
V207 -> 73.01432233846664 %
V208 -> 73.08517419887072 %
V209 -> 73.08517419887072 %
V210 -> 73.08517419887072 %
V211 -> 73.01432233846664 %
V212 -> 73.01432233846664 %
V213 -> 73.01432233846664 %
V214 -> 73.01432233846664 %
V215 -> 73.01432233846664 %
V216 -> 73.01432233846664 %
V217 -> 74.98909591841971 %
V218 -> 74.98909591841971 %
V219 -> 74.98909591841971 %
V220 -> 72.89945943385614 %
V221 -> 72.89945943385614 %
V222 -> 72.89945943385614 %
V223 -> 74.98909591841971 %
V224 -> 74.98909591841971 %
V225 -> 74.98909591841971 %
V226 -> 74.98909591841971 %
V227 -> 72.89945943385614 %
V228 -> 74.98909591841971 %
V229 -> 74.98909591841971 %
V230 -> 74.98909591841971 %
V231 -> 74.98909591841971 %
V232 -> 74.98909591841971 %
V233 -> 74.98909591841971 %
V234 -> 72.89945943385614 %
V235 -> 74.98909591841971 %
V236 -> 74.98909591841971 %
V237 -> 74.98909591841971 %
V238 -> 72.89945943385614 %
V239 -> 72.89945943385614 %
V240 -> 74.98909591841971 %
V241 -> 74.98909591841971 %
V242 -> 74.98909591841971 %
V243 -> 74.98909591841971 %
V244 -> 74.98909591841971 %
V245 -> 72.89945943385614 %
V246 -> 74.98909591841971 %
V247 -> 74.98909591841971 %
V248 -> 74.98909591841971 %
V249 -> 74.98909591841971 %
V250 -> 72.89945943385614 %
V251 -> 72.89945943385614 %
V252 -> 74.98909591841971 %
V253 -> 74.98909591841971 %
V254 -> 74.98909591841971 %
V255 -> 72.89945943385614 %
V256 -> 72.89945943385614 %
V257 -> 74.98909591841971 %
V258 -> 74.98909591841971 %
V259 -> 72.89945943385614 %
V260 -> 74.98909591841971 %
V261 -> 74.98909591841971 %
V262 -> 74.98909591841971 %
V263 -> 74.98909591841971 %
V264 -> 74.98909591841971 %
V265 -> 74.98909591841971 %
V266 -> 74.98909591841971 %
V267 -> 74.98909591841971 %
V268 -> 74.98909591841971 %
V269 -> 74.98909591841971 %
V270 -> 72.89945943385614 %
V271 -> 72.89945943385614 %
V272 -> 72.89945943385614 %
V273 -> 74.98909591841971 %
V274 -> 74.98909591841971 %
V275 -> 74.98909591841971 %
V276 -> 74.98909591841971 %
V277 -> 74.98909591841971 %
V278 -> 74.98909591841971 %
V279 -> 0.0005920768278891869 %
V280 -> 0.0005920768278891869 %
V281 -> 1.1902717829998954 %
V282 -> 1.1902717829998954 %
V283 -> 1.1902717829998954 %
V284 -> 0.0005920768278891869 %
V285 -> 0.0005920768278891869 %
V286 -> 0.0005920768278891869 %
V287 -> 0.0005920768278891869 %
V288 -> 1.1902717829998954 %
V289 -> 1.1902717829998954 %
V290 -> 0.0005920768278891869 %
V291 -> 0.0005920768278891869 %
V292 -> 0.0005920768278891869 %
V293 -> 0.0005920768278891869 %
V294 -> 0.0005920768278891869 %
V295 -> 0.0005920768278891869 %
V296 -> 1.1902717829998954 %
V297 -> 0.0005920768278891869 %
V298 -> 0.0005920768278891869 %
V299 -> 0.0005920768278891869 %
V300 -> 1.1902717829998954 %
V301 -> 1.1902717829998954 %
V302 -> 0.0005920768278891869 %
V303 -> 0.0005920768278891869 %
V304 -> 0.0005920768278891869 %
V305 -> 0.0005920768278891869 %
V306 -> 0.0005920768278891869 %
V307 -> 0.0005920768278891869 %
V308 -> 0.0005920768278891869 %
V309 -> 0.0005920768278891869 %
V310 -> 0.0005920768278891869 %
V311 -> 0.0005920768278891869 %
V312 -> 0.0005920768278891869 %
V313 -> 1.1902717829998954 %
V314 -> 1.1902717829998954 %
V315 -> 1.1902717829998954 %
V316 -> 0.0005920768278891869 %
V317 -> 0.0005920768278891869 %
V318 -> 0.0005920768278891869 %
V319 -> 0.0005920768278891869 %
V320 -> 0.0005920768278891869 %
V321 -> 0.0005920768278891869 %
V322 -> 84.91565865586719 %
V323 -> 84.91565865586719 %
V324 -> 84.91565865586719 %
V325 -> 84.91565865586719 %
V326 -> 84.91565865586719 %
V327 -> 84.91565865586719 %
V328 -> 84.91565865586719 %
V329 -> 84.91565865586719 %
V330 -> 84.91565865586719 %
V331 -> 84.91565865586719 %
V332 -> 84.91565865586719 %
V333 -> 84.91565865586719 %
V334 -> 84.91565865586719 %
V335 -> 84.91565865586719 %
V336 -> 84.91565865586719 %
V337 -> 84.91565865586719 %
V338 -> 84.91565865586719 %
V339 -> 84.91565865586719 %

In [8]:
drop_identity = ['id-07','id-08','id-21','id-22','id-23','id-24','id-25','id-26','id-27','id-30','id-31','id-33','id-34','id-36','id-37','DeviceInfo']

In [9]:
drop_identity

['id-07',
 'id-08',
 'id-21',
 'id-22',
 'id-23',
 'id-24',
 'id-25',
 'id-26',
 'id-27',
 'id-30',
 'id-31',
 'id-33',
 'id-34',
 'id-36',
 'id-37',
 'DeviceInfo']

In [10]:
for value in drop_identity:
    df_i.pop(value)

In [11]:
drop_trans = ['dist2', 'P_emaildomain', 'R_emaildomain','D6',
 'D7',
 'D8',
 'D9',
 'D12',
 'D13',
 'D14',
 'V138',
 'V139',
 'V140',
 'V141',
 'V142',
 'V143',
 'V144',
 'V145',
 'V146',
 'V147',
 'V148',
 'V149',
 'V150',
 'V151',
 'V152',
 'V153',
 'V154',
 'V155',
 'V156',
 'V157',
 'V158',
 'V159',
 'V160',
 'V161',
 'V162',
 'V163',
 'V164',
 'V165',
 'V166',
 'V167',
 'V168',
 'V169',
 'V170',
 'V171',
 'V172',
 'V173',
 'V174',
 'V175',
 'V176',
 'V177',
 'V178',
 'V179',
 'V180',
 'V181',
 'V182',
 'V183',
 'V184',
 'V185',
 'V186',
 'V187',
 'V188',
 'V189',
 'V190',
 'V191',
 'V192',
 'V193',
 'V194',
 'V195',
 'V196',
 'V197',
 'V198',
 'V199',
 'V200',
 'V201',
 'V202',
 'V203',
 'V204',
 'V205',
 'V206',
 'V207',
 'V208',
 'V209',
 'V210',
 'V211',
 'V212',
 'V213',
 'V214',
 'V215',
 'V216',
 'V217',
 'V218',
 'V219',
 'V220',
 'V221',
 'V222',
 'V223',
 'V224',
 'V225',
 'V226',
 'V227',
 'V228',
 'V229',
 'V230',
 'V231',
 'V232',
 'V233',
 'V234',
 'V235',
 'V236',
 'V237',
 'V238',
 'V239',
 'V240',
 'V241',
 'V242',
 'V243',
 'V244',
 'V245',
 'V246',
 'V247',
 'V248',
 'V249',
 'V250',
 'V251',
 'V252',
 'V253',
 'V254',
 'V255',
 'V256',
 'V257',
 'V258',
 'V259',
 'V260',
 'V261',
 'V262',
 'V263',
 'V264',
 'V265',
 'V266',
 'V267',
 'V268',
 'V269',
 'V270',
 'V271',
 'V272',
 'V273',
 'V274',
 'V275',
 'V276',
 'V277',
 'V278',
 'V322',
 'V323',
 'V324',
 'V325',
 'V326',
 'V327',
 'V328',
 'V329',
 'V330',
 'V331',
 'V332',
 'V333',
 'V334',
 'V335',
 'V336',
 'V337',
 'V338',
 'V339']

In [12]:
len(drop_trans)

169

In [13]:
for value in drop_trans:
    df_t.pop(value)

In [14]:
test_pre_set = df_t.merge(df_i, on='TransactionID', how='left')

In [15]:
test_pre_set

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,dist1,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,...,V321,id-01,id-02,id-03,id-04,id-05,id-06,id-09,id-10,id-11,id-12,id-13,id-14,id-15,id-16,id-17,id-18,id-19,id-20,id-28,id-29,id-32,id-35,id-38,DeviceType
0,3663549,18403224,31.950,W,10409,111.0,150.0,visa,226.0,debit,170.0,87.0,1.0,6.0,6.0,0.0,0.0,3.0,4.0,0.0,0.0,6.0,0.0,5.0,1.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3663550,18403263,49.000,W,4272,111.0,150.0,visa,226.0,debit,299.0,87.0,4.0,3.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,1.0,1.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3663551,18403310,171.000,W,4476,574.0,150.0,visa,226.0,debit,472.0,87.0,2635.0,2.0,2.0,0.0,0.0,0.0,5.0,0.0,0.0,4.0,0.0,2.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3663552,18403310,284.950,W,10989,360.0,150.0,visa,166.0,debit,205.0,87.0,17.0,5.0,2.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,2.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3663553,18403317,67.950,W,18018,452.0,150.0,mastercard,117.0,debit,264.0,87.0,6.0,6.0,6.0,0.0,0.0,2.0,5.0,0.0,0.0,5.0,0.0,6.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506686,4170235,34214279,94.679,C,13832,375.0,185.0,mastercard,224.0,debit,284.0,60.0,NaN,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506687,4170236,34214287,12.173,C,3154,408.0,185.0,mastercard,224.0,debit,NaN,NaN,NaN,1.0,3.0,0.0,1.0,0.0,1.0,1.0,2.0,0.0,2.0,1.0,1.0,...,0.0,-45.0,266704.0,NaN,NaN,-3.0,-10.0,NaN,NaN,100.0,NotFound,27.0,NaN,New,NotFound,225.0,15.0,176.0,507.0,New,NotFound,NaN,F,F,mobile
506688,4170237,34214326,49.000,W,16661,490.0,150.0,visa,226.0,debit,327.0,87.0,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506689,4170238,34214337,202.000,W,16621,516.0,150.0,mastercard,224.0,debit,177.0,87.0,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506690,4170239,34214345,24.346,C,5713,168.0,144.0,visa,147.0,credit,NaN,NaN,NaN,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,0.0,-10.0,692090.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,NotFound,27.0,NaN,Found,Found,225.0,NaN,266.0,127.0,Found,Found,NaN,F,F,mobile

In [16]:
test_pre_set.pop('TransactionID')

0         3663549
1         3663550
2         3663551
3         3663552
4         3663553
           ...
506686    4170235
506687    4170236
506688    4170237
506689    4170238
506690    4170239
Name: TransactionID, Length: 506691, dtype: int64

In [17]:
# remove all categorical features
cat_feat =[]

for column in test_pre_set:
    if test_pre_set[column].dtypes == 'O':
        cat_feat.append(column)

In [18]:
cat_feat

['ProductCD',
 'card4',
 'card6',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'id-12',
 'id-15',
 'id-16',
 'id-28',
 'id-29',
 'id-35',
 'id-38',
 'DeviceType']

In [19]:
df_n = test_pre_set.drop(columns = cat_feat)

In [20]:
df_n.shape

(506691, 227)

In [21]:
df_n.columns

Index(['TransactionDT', 'TransactionAmt', 'card1', 'card2', 'card3', 'card5',
       'addr1', 'addr2', 'dist1', 'C1',
       ...
       'id-09', 'id-10', 'id-11', 'id-13', 'id-14', 'id-17', 'id-18', 'id-19',
       'id-20', 'id-32'],
      dtype='object', length=227)

### Fill in missing values

In [22]:
for column in df_n:
    btao = df_n[column].isna().sum()
    btao2 = (btao * 100)/len(df_n)
    if btao2 > 0:
        df_n[column].fillna(float(df_n[column].mean()), inplace=True)

In [23]:
for column in df_n:
    btao = df_n[column].isna().sum()
    btao2 = (btao * 100)/len(df_n)
    print(column + " -> " + str(btao2) + ' %')

TransactionDT -> 0.0 %
TransactionAmt -> 0.0 %
card1 -> 0.0 %
card2 -> 0.0 %
card3 -> 0.0 %
card5 -> 0.0 %
addr1 -> 0.0 %
addr2 -> 0.0 %
dist1 -> 0.0 %
C1 -> 0.0 %
C2 -> 0.0 %
C3 -> 0.0 %
C4 -> 0.0 %
C5 -> 0.0 %
C6 -> 0.0 %
C7 -> 0.0 %
C8 -> 0.0 %
C9 -> 0.0 %
C10 -> 0.0 %
C11 -> 0.0 %
C12 -> 0.0 %
C13 -> 0.0 %
C14 -> 0.0 %
D1 -> 0.0 %
D2 -> 0.0 %
D3 -> 0.0 %
D4 -> 0.0 %
D5 -> 0.0 %
D10 -> 0.0 %
D11 -> 0.0 %
D15 -> 0.0 %
V1 -> 0.0 %
V2 -> 0.0 %
V3 -> 0.0 %
V4 -> 0.0 %
V5 -> 0.0 %
V6 -> 0.0 %
V7 -> 0.0 %
V8 -> 0.0 %
V9 -> 0.0 %
V10 -> 0.0 %
V11 -> 0.0 %
V12 -> 0.0 %
V13 -> 0.0 %
V14 -> 0.0 %
V15 -> 0.0 %
V16 -> 0.0 %
V17 -> 0.0 %
V18 -> 0.0 %
V19 -> 0.0 %
V20 -> 0.0 %
V21 -> 0.0 %
V22 -> 0.0 %
V23 -> 0.0 %
V24 -> 0.0 %
V25 -> 0.0 %
V26 -> 0.0 %
V27 -> 0.0 %
V28 -> 0.0 %
V29 -> 0.0 %
V30 -> 0.0 %
V31 -> 0.0 %
V32 -> 0.0 %
V33 -> 0.0 %
V34 -> 0.0 %
V35 -> 0.0 %
V36 -> 0.0 %
V37 -> 0.0 %
V38 -> 0.0 %
V39 -> 0.0 %
V40 -> 0.0 %
V41 -> 0.0 %
V42 -> 0.0 %
V43 -> 0.0 %
V44 -> 0.0 %
V45 -> 0.0 %
V46 -> 0.0 %
V47 -> 0.0 %
V48 -> 0.0 %
V49 -> 0.0 %
V50 -> 0.0 %
V51 -> 0.0 %
V52 -> 0.0 %
V53 -> 0.0 %
V54 -> 0.0 %
V55 -> 0.0 %
V56 -> 0.0 %
V57 -> 0.0 %
V58 -> 0.0 %
V59 -> 0.0 %
V60 -> 0.0 %
V61 -> 0.0 %
V62 -> 0.0 %
V63 -> 0.0 %
V64 -> 0.0 %
V65 -> 0.0 %
V66 -> 0.0 %
V67 -> 0.0 %
V68 -> 0.0 %
V69 -> 0.0 %
V70 -> 0.0 %
V71 -> 0.0 %
V72 -> 0.0 %
V73 -> 0.0 %
V74 -> 0.0 %
V75 -> 0.0 %
V76 -> 0.0 %
V77 -> 0.0 %
V78 -> 0.0 %
V79 -> 0.0 %
V80 -> 0.0 %
V81 -> 0.0 %
V82 -> 0.0 %
V83 -> 0.0 %
V84 -> 0.0 %
V85 -> 0.0 %
V86 -> 0.0 %
V87 -> 0.0 %
V88 -> 0.0 %
V89 -> 0.0 %
V90 -> 0.0 %
V91 -> 0.0 %
V92 -> 0.0 %
V93 -> 0.0 %
V94 -> 0.0 %
V95 -> 0.0 %
V96 -> 0.0 %
V97 -> 0.0 %
V98 -> 0.0 %
V99 -> 0.0 %
V100 -> 0.0 %
V101 -> 0.0 %
V102 -> 0.0 %
V103 -> 0.0 %
V104 -> 0.0 %
V105 -> 0.0 %
V106 -> 0.0 %
V107 -> 0.0 %
V108 -> 0.0 %
V109 -> 0.0 %
V110 -> 0.0 %
V111 -> 0.0 %
V112 -> 0.0 %
V113 -> 0.0 %
V114 -> 0.0 %
V115 -> 0.0 %
V116 -> 0.0 %
V117 -> 0.0 %
V118 -> 0.0 %
V119 -> 0.0 %
V120 -> 0.0 %
V121 -> 0.0 %
V122 -> 0.0 %
V123 -> 0.0 %
V124 -> 0.0 %
V125 -> 0.0 %
V126 -> 0.0 %
V127 -> 0.0 %
V128 -> 0.0 %
V129 -> 0.0 %
V130 -> 0.0 %
V131 -> 0.0 %
V132 -> 0.0 %
V133 -> 0.0 %
V134 -> 0.0 %
V135 -> 0.0 %
V136 -> 0.0 %
V137 -> 0.0 %
V279 -> 0.0 %
V280 -> 0.0 %
V281 -> 0.0 %
V282 -> 0.0 %
V283 -> 0.0 %
V284 -> 0.0 %
V285 -> 0.0 %
V286 -> 0.0 %
V287 -> 0.0 %
V288 -> 0.0 %
V289 -> 0.0 %
V290 -> 0.0 %
V291 -> 0.0 %
V292 -> 0.0 %
V293 -> 0.0 %
V294 -> 0.0 %
V295 -> 0.0 %
V296 -> 0.0 %
V297 -> 0.0 %
V298 -> 0.0 %
V299 -> 0.0 %
V300 -> 0.0 %
V301 -> 0.0 %
V302 -> 0.0 %
V303 -> 0.0 %
V304 -> 0.0 %
V305 -> 0.0 %
V306 -> 0.0 %
V307 -> 0.0 %
V308 -> 0.0 %
V309 -> 0.0 %
V310 -> 0.0 %
V311 -> 0.0 %
V312 -> 0.0 %
V313 -> 0.0 %
V314 -> 0.0 %
V315 -> 0.0 %
V316 -> 0.0 %
V317 -> 0.0 %
V318 -> 0.0 %
V319 -> 0.0 %
V320 -> 0.0 %
V321 -> 0.0 %
id-01 -> 0.0 %
id-02 -> 0.0 %
id-03 -> 0.0 %
id-04 -> 0.0 %
id-05 -> 0.0 %
id-06 -> 0.0 %
id-09 -> 0.0 %
id-10 -> 0.0 %
id-11 -> 0.0 %
id-13 -> 0.0 %
id-14 -> 0.0 %
id-17 -> 0.0 %
id-18 -> 0.0 %
id-19 -> 0.0 %
id-20 -> 0.0 %
id-32 -> 0.0 %

We now have our test set readied as per all the modelling we have done on our train data  except correlation_study.ipynb to see the features dropped after feature correlation.

In [26]:
df_n.to_csv('test_df.csv',index=False)

In [27]:
sample = pd.read_csv('test_df.csv')

sample.columns

Index(['TransactionDT', 'TransactionAmt', 'card1', 'card2', 'card3', 'card5',
       'addr1', 'addr2', 'dist1', 'C1',
       ...
       'id-09', 'id-10', 'id-11', 'id-13', 'id-14', 'id-17', 'id-18', 'id-19',
       'id-20', 'id-32'],
      dtype='object', length=227)